//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp8.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raspisanie
    {
        public int NumCabinet { get; set; }
        public int KodPridmeta { get; set; }
        public int NumberTeacher { get; set; }
        public string Fio { get; set; }
    
        public virtual Pridmet Pridmet { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
